version: '2'
services:
    redis:
        image: redis
        ports:
            - "63792:6379"
        networks:
            - app
    adminer:
      image: adminer
      ports:
        - "8091:8080"
    mysql:
        image: mysql:5.7.34
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shop160_db
            MYSQL_PASSWORD: root
        networks:
            - app
        volumes:
            - ./cache/mysql:/var/lib/mysql
        ports:
            - "33065:3306" 
    security:
        build: ./source
        links:
            - redis
        ports:
            - "5002:3500"
        depends_on:
            - mysql
        environment:
            - DATABASE_HOST=db
            - redis_server_addr=redis
        volumes:
            - ./source:/app
            - /app/node_modules
        networks:
            - app

networks:
    app:
        driver: bridge