version: '2'
services:
    redis:
        image: redis
        ports:
            - "63792:6379"
        networks:
            - app
    adminer:
      image: adminer
      ports:
        - "8091:8080"
    mysql:
        image: mysql:5.7.27
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "/dev/null:/usr/bin/mysql_ssl_rsa_setup"
        ports:
            - "33065:3306"
        environment:
            - MYSQL_DATABASE=shop160_db
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        networks:
            - app
        expose:
            - "33065"
    security:
        build: ./source
        links:
            - redis
        ports:
            - "5002:3500"
        depends_on:
            - mysql
        environment:
            - DATABASE_HOST=db
            - redis_server_addr=redis
        volumes:
            - ./source:/app
        networks:
            - app

networks:
    app:
        driver: bridge